name: flutter_tools_api
description: An api for building Flutter tools extensions
homepage: https://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.0 <3.0.0"

# This package intentionally has no direct dependencies.

# PUBSPEC CHECKSUM: c4bc
