name: flutter_tools
description: Tools for building Flutter applications
homepage: https://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  frontend_server: any
  archive: 2.0.11
  args: 1.5.2
  # dwds: 0.8.1
  completion: 0.2.1+1
  coverage: 0.13.3+1
  crypto: 2.1.3
  file: 5.1.0
  http: 0.12.0+2
  intl: 0.16.0
  json_rpc_2: 2.1.0
  # linter: 0.1.101
  meta: 1.1.8
  multicast_dns: 0.2.2
  mustache: 1.1.1
  package_config: 1.1.0
  platform: 2.2.1
  plugin: 0.2.0+3
  process: 3.0.12
  quiver: 2.0.5
  stack_trace: 1.9.3
  stream_channel: 2.0.0
  usage: 3.4.1
  vm_service_client: 0.2.6+2
  web_socket_channel: 1.1.0
  webkit_inspection_protocol: 0.5.0
  xml: 3.5.0
  yaml: 2.2.0
  flutter_goldens_client:
    path: ../flutter_goldens_client

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.2.11
  # test_core: 0.2.15

  # Code generation dependencies
  # build_runner_core: 4.2.0
  # dart_style: 1.3.3
  # code_builder: 3.2.1
  # build: 1.2.2
  # build_modules: 2.7.0
  build_daemon: 2.1.2
  # build_web_compilers: 2.7.1

  # analyzer: 0.38.5 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

dev_dependencies:
  collection: 1.14.11

dependency_overrides:
  frontend_server:
    path: /Users/jonahwilliams/Documents/engine/src/out/host_debug_unopt/gen/dart-pkg/frontend_server
  vm:
    path: /Users/jonahwilliams/Documents/engine/src/out/host_debug_unopt/gen/dart-pkg/vm
  build_integration:
    path: /Users/jonahwilliams/Documents/engine/src/out/host_debug_unopt/gen/dart-pkg/build_integration
  dev_compiler:
    path: /Users/jonahwilliams/Documents/engine/src/out/host_debug_unopt/gen/dart-pkg/dev_compiler
  front_end:
    path: /Users/jonahwilliams/Documents/engine/src/out/host_debug_unopt/gen/dart-pkg/front_end
  kernel:
    path: /Users/jonahwilliams/Documents/engine/src/out/host_debug_unopt/gen/dart-pkg/kernel
  _fe_analyzer_shared:
    path: /Users/jonahwilliams/Documents/engine/src/out/host_debug_unopt/gen/dart-pkg/_fe_analyzer_shared
dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true

# PUBSPEC CHECKSUM: de88
