name: flutter_tools
description: Tools for building Flutter applications
homepage: https://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: 2.0.10
  args: 1.5.2
  dwds: 0.5.0
  completion: 0.2.1+1
  coverage: 0.13.2
  crypto: 2.1.1+1
  file: 5.0.8+1
  http: 0.12.0+2
  intl: 0.15.8
  json_rpc_2: 2.1.0
  linter: 0.1.93
  meta: 1.1.7
  multicast_dns: 0.2.0
  mustache: 1.1.1
  package_config: 1.0.5
  platform: 2.2.1
  plugin: 0.2.0+3
  process: 3.0.11
  quiver: 2.0.5
  stack_trace: 1.9.3
  stream_channel: 2.0.0
  usage: 3.4.1
  vm_service_client: 0.2.6+2
  web_socket_channel: 1.0.15
  webkit_inspection_protocol: 0.4.2
  xml: 3.5.0
  yaml: 2.1.16
  flutter_goldens_client:
    path: ../flutter_goldens_client
  protobuf: 0.13.15

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.2.5

  # Code generation dependencies
  build_runner_core: 3.0.9
  dart_style: 1.2.9
  code_builder: 3.2.0
  build: 1.1.5
  build_modules: 2.4.2
  build_daemon: 2.0.0
  build_web_compilers: 2.2.2

  # Frontend dependencies
  vm: any

dev_dependencies:
  collection: 1.14.11

dependency_overrides:
  analyzer:
    path: /Users/jonahwilliams/Documents/engine/src/third_party/dart/pkg/analyzer
  kernel:
    path: /Users/jonahwilliams/Documents/engine/src/third_party/dart/pkg/kernel
  front_end:
    path: /Users/jonahwilliams/Documents/engine/src/third_party/dart/pkg/front_end
  vm:
    path: /Users/jonahwilliams/Documents/engine/src/third_party/dart/pkg/vm

dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true


# PUBSPEC CHECKSUM: 3394
