name: codegen
description: A test of Flutter integrating code generation.

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  json_annotation:
  # TODO(jonahwilliams): replace with pub version when everything is compatible
  inject:
    git:
      url: https://github.com/jonahwilliams/inject.dart
      path: package/inject

dev_dependencies:
  test: 1.5.3

builders:
  # TODO(jonahwilliams): replace with pub version when everything is compatible
  inject_generator:
    git:
      url: https://github.com/jonahwilliams/inject.dart
      path: package/inject_generator
  json_serializable:
  json_widget:
    path: /Users/jonahwilliams/Documents/json_widget

flutter:
  uses-material-design: true

